[book]
authors = ["authors of flutter_rust_bridge, see GitHub README.md for detailed contributions"]
language = "en"
multilingual = false
src = "src"
title = "flutter_rust_bridge"

[build]
extra-watch-dirs = ["po"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.gettext]
after = ["links"]

[output.html]
# curly-quotes = true
# additional-js = ["speaker-notes.js"]
# additional-css = ["svgbob.css", "speaker-notes.css", "language-picker.css"]
additional-css = ["theme/language-picker.css"]
site-url = "/flutter_rust_bridge/"
git-repository-url = "https://github.com/trdthg/flutter_rust_bridge"
edit-url-template = "https://github.com/trdthg/flutter_rust_bridge/edit/main/{path}"
