[book]
authors = ["authors of flutter_rust_bridge, see GitHub README.md for detailed contributions"]
language = "en"
multilingual = false
src = "src"
title = "flutter_rust_bridge"

[build]
extra-watch-dirs = ["po"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.gettext]
after = ["links"]